spring.application.name=correction

# spring.datasource.url=jdbc:postgresql://localhost:5432/correction-feuille
spring.datasource.username=postgres
spring.datasource.password=mdp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server.port=8080